"groups":
- "name": "argo-cd"
  "rules":
  - "alert": "ArgoCdAppSyncFailed"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-cd-application-overview-kask/argocd-application-overview?var-dest_server={{ $labels.dest_server }}&var-project={{ $labels.project }}&var-application={{ $labels.name }}"
      "description": "The application {{ $labels.dest_server }}/{{ $labels.project }}/{{ $labels.name }} has failed to sync with the status {{ $labels.phase }} the past 10m."
      "summary": "An ArgoCD Application has Failed to Sync."
    "expr": |
      sum(
        round(
          increase(
            argocd_app_sync_total{
              job=~".*",
              phase!="Succeeded"
            }[10m]
          )
        )
      ) by (cluster, job, dest_server, project, name, phase) > 0
    "for": "1m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoCdAppUnhealthy"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-cd-application-overview-kask/argocd-application-overview?var-dest_server={{ $labels.dest_server }}&var-project={{ $labels.project }}&var-application={{ $labels.name }}"
      "description": "The application {{ $labels.dest_server }}/{{ $labels.project }}/{{ $labels.name }} is unhealthy with the health status {{ $labels.health_status }} for the past 15m."
      "summary": "An ArgoCD Application is Unhealthy."
    "expr": |
      sum(
        argocd_app_info{
          job=~".*",
          health_status!~"Healthy|Progressing",
          name!~""
        }
      ) by (cluster, job, dest_server, project, name, health_status)
      > 0
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoCdAppOutOfSync"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-cd-application-overview-kask/argocd-application-overview?var-dest_server={{ $labels.dest_server }}&var-project={{ $labels.project }}&var-application={{ $labels.name }}"
      "description": "The application {{ $labels.dest_server }}/{{ $labels.project }}/{{ $labels.name }} is out of sync with the sync status {{ $labels.sync_status }} for the past 15m."
      "summary": "An ArgoCD Application is Out Of Sync."
    "expr": |
      sum(
        argocd_app_info{
          job=~".*",
          sync_status!="Synced"
        }
      ) by (cluster, job, dest_server, project, name, sync_status)
      > 0
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "ArgoCdAppAutoSyncDisabled"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-cd-application-overview-kask/argocd-application-overview?var-dest_server={{ $labels.dest_server }}&var-project={{ $labels.project }}&var-application={{ $labels.name }}"
      "description": "The application {{ $labels.dest_server }}/{{ $labels.project }}/{{ $labels.name }} has autosync disabled for the past 2h."
      "summary": "An ArgoCD Application has AutoSync Disabled."
    "expr": |
      sum(
        argocd_app_info{
          job=~".*",
          autosync_enabled!="true",
          name!~""
        }
      ) by (cluster, job, dest_server, project, name, autosync_enabled)
      > 0
    "for": "2h"
    "labels":
      "severity": "warning"
  - "alert": "ArgoCdNotificationDeliveryFailed"
    "annotations":
      "dashboard_url": "https://grafana.com/d/argo-cd-notifications-overview-kask/argocd-notifications-overview?var-job={{ $labels.job }}&var-exported_service={{ $labels.exported_service }}"
      "description": "The notification job {{ $labels.job }} has failed to deliver to {{ $labels.exported_service }} for the past 10m."
      "summary": "ArgoCD Notification Delivery Failed."
    "expr": |
      sum(
        round(
          increase(
            argocd_notifications_deliveries_total{
              job=~".*",
              succeeded!="true"
            }[10m]
          )
        )
      ) by (cluster, job, exported_service, succeeded) > 0
    "for": "1m"
    "labels":
      "severity": "warning"
